<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Donor Glucose and Delayed Graft Dysfunction in Liver Transplantation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="project_files/libs/clipboard/clipboard.min.js"></script>
<script src="project_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="project_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="project_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="project_files/libs/quarto-html/popper.min.js"></script>
<script src="project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="project_files/libs/quarto-html/anchor.min.js"></script>
<link href="project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="project_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="project_files/libs/bootstrap/bootstrap-8c543e4039884b26c7b0567813ae3237.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="project_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="project_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head><body class="fullcontent quarto-light">\usepackage{booktabs}
\usepackage{float}
\floatplacement{table}{H}

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>





<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Donor Glucose and Delayed Graft Dysfunction in Liver Transplantation</h1>
<p class="subtitle lead">Does Donor Risk Index Modify the Association?</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Delayed graft dysfunction (DGD) is a complication that can occur following liver transplantation, and is generally associated with longer hospital stays, higher mortality, and worse long-term graft survival. Understanding what predicts DGD matters both for patient outcomes and for decisions about which donor organs to accept.</p>
<p>One commonly used tool for assessing donor organ quality is the Donor Risk Index (DRI), a composite score that takes into account factors like donor age, cause of death, and organ type to estimate the likelihood of graft failure. Higher DRI values indicate higher-risk donations. While DRI has been used to predict transplant outcomes, it is based on demographic and clinical information and does not include real-time physiological measurements from the donor.</p>
<p>Donor glucose is one variable that might provide additional information. High glucose levels in critically ill patients can be a sign of physiological stress, which could potentially affect organ viability before transplantation. That said, whether donor glucose is actually associated with DGD — and whether that relationship changes depending on how risky the donor already is by DRI — is not well established in the literature we reviewed.</p>
<p>This study looks at both of these questions using data from 572 liver transplant donors. The dataset includes donor glucose levels (recorded as a time-weighted average and log-transformed for analysis), the Donor Risk Index, donor sex, and whether delayed graft dysfunction occurred.</p>
<p><strong>Research question:</strong> Does donor glucose level predict delayed graft dysfunction in liver transplantation, and does this association differ by donor risk index?</p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<section id="model-specification" class="level2">
<h2 class="anchored" data-anchor-id="model-specification">Model Specification</h2>
<p>Because delayed graft dysfunction is a binary outcome (1 = dysfunction, 0 = no dysfunction), we used logistic regression to model the probability of DGD. This is a standard approach for binary outcomes and lets us estimate how each predictor is associated with the odds of dysfunction while holding the others constant.</p>
<p>We fit two models. The first includes an interaction term between log-transformed glucose and DRI. We included this interaction because we wanted to test whether the relationship between glucose and DGD might depend on how risky the donor already is — for example, glucose might matter more for high-risk donors than low-risk ones:</p>
<p><span class="math display">\[\text{logit}(P(\text{DGD})) = \beta_0 + \beta_1\log_2(\text{glucose}) + \beta_2\text{DRI} + \beta_3\text{sex} + \beta_4\log_2(\text{glucose})\times\text{DRI}\]</span></p>
<p>where <span class="math inline">\(\text{logit}(P(\text{DGD}))\)</span> is the log-odds of delayed graft dysfunction, <span class="math inline">\(\log_2(\text{glucose})\)</span> is the log base-2 transformed time-weighted average donor glucose, <span class="math inline">\(\text{DRI}\)</span> is the Donor Risk Index, <span class="math inline">\(\text{sex}\)</span> is donor sex (female = 1), and the interaction term <span class="math inline">\(\log_2(\text{glucose}) \times \text{DRI}\)</span> captures whether the glucose effect differs across DRI levels.</p>
<p>We also fit a reduced model without the interaction term, to look at the independent effect of each predictor:</p>
<p><span class="math display">\[\text{logit}(P(\text{DGD})) = \beta_0 + \beta_1\log_2(\text{glucose}) + \beta_2\text{DRI} + \beta_3\text{sex}\]</span></p>
<p>We then compared the two models using a likelihood ratio test (LRT) to see whether adding the interaction term meaningfully improved model fit. If the test came back non-significant (<span class="math inline">\(p &gt; 0.05\)</span>), we would conclude there is not enough evidence for an interaction and stick with the simpler model.</p>
</section>
<section id="choice-of-predictors-and-transformations" class="level2">
<h2 class="anchored" data-anchor-id="choice-of-predictors-and-transformations">Choice of Predictors and Transformations</h2>
<p>Glucose was log-transformed (base 2) before modeling because the raw values were right-skewed. The log<span class="math inline">\(_2\)</span> scale is also convenient for interpretation: a one-unit increase corresponds to a doubling of the original glucose value.</p>
<p>We included donor sex as a covariate based on prior literature suggesting it may be related to graft outcomes. DRI was kept as a continuous variable rather than grouped into categories, since collapsing it would lose information.</p>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>Logistic regression requires a few key assumptions: that the log-odds of the outcome is approximately linear in each continuous predictor, that observations are independent, and that predictors are not perfectly collinear with each other.</p>
<p>We assessed linearity by looking at the shape of the fitted logistic curve, which appeared smooth and monotonic — consistent with the linearity assumption, though we did not run formal diagnostics. Independence seems reasonable since each row in the dataset is a separate donor-recipient pair. The three predictors capture different aspects of the donor (metabolic, composite risk, and demographic), so perfect collinearity is unlikely. It is worth noting that 135 observations were dropped due to missing data, leaving 437 complete cases, which is still a reasonable sample size for this kind of model.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="model-comparison-likelihood-ratio-test" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison-likelihood-ratio-test">Model Comparison: Likelihood Ratio Test</h2>
<p>The likelihood ratio test comparing the full model to the reduced model returned a <span class="math inline">\(p\)</span>-value of 0.32. This means we do not have sufficient evidence at the 0.05 significance level to conclude that the interaction between glucose and DRI improves model fit. In other words, the data do not support the idea that the effect of glucose on DGD changes depending on the donor’s risk level. We proceeded with the reduced model for the rest of the analysis.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Likelihood Ratio Test: Full vs. Reduced Model</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Resid. df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Resid. Dev.</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">$\Delta$ Dev.</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">$p$-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Reduced (no interaction)</td>
<td style="text-align: right;">433</td>
<td style="text-align: right;">492.50</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">Full (with interaction)</td>
<td style="text-align: right;">432</td>
<td style="text-align: right;">491.51</td>
<td style="text-align: left;">0.988</td>
<td style="text-align: left;">0.320</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Null deviance = 503.72 on 436 df. 135 observations removed due to missingness.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</section>
<section id="reduced-model-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="reduced-model-coefficients">Reduced Model Coefficients</h2>
<p>Looking at the reduced model, donor risk index was the only statistically significant predictor (estimate = 0.958, SE = 0.328, <span class="math inline">\(z\)</span> = 2.92, <span class="math inline">\(p\)</span> = 0.003). Donor glucose (<span class="math inline">\(p\)</span> = 0.282) and donor sex (<span class="math inline">\(p\)</span> = 0.878) were not significant at the 0.05 level.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Reduced Logistic Regression Model: Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">$z$ value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">$p$-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-4.480</td>
<td style="text-align: right;">1.994</td>
<td style="text-align: right;">-2.246</td>
<td style="text-align: left;">0.025 *</td>
</tr>
<tr class="even">
<td style="text-align: left;">$\log_2$(glucose)</td>
<td style="text-align: right;">0.284</td>
<td style="text-align: right;">0.263</td>
<td style="text-align: right;">1.076</td>
<td style="text-align: left;">0.282</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">donorrisk</td>
<td style="text-align: right; font-weight: bold;">0.958</td>
<td style="text-align: right; font-weight: bold;">0.328</td>
<td style="text-align: right; font-weight: bold;">2.925</td>
<td style="text-align: left; font-weight: bold;">0.003 **</td>
</tr>
<tr class="even">
<td style="text-align: left;">sex (female)</td>
<td style="text-align: right;">-0.037</td>
<td style="text-align: right;">0.241</td>
<td style="text-align: right;">-0.153</td>
<td style="text-align: left;">0.878</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> ** $p &lt; 0.01$, * $p &lt; 0.05$. AIC = 500.5.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</section>
<section id="effect-size-and-confidence-interval-for-donor-risk" class="level2">
<h2 class="anchored" data-anchor-id="effect-size-and-confidence-interval-for-donor-risk">Effect Size and Confidence Interval for Donor Risk</h2>
<p>To better understand the size of the DRI effect, we exponentiated the coefficient to get an odds ratio of approximately 2.61 (95% CI: 1.40 to 5.07). This suggests that for each one-unit increase in DRI, the estimated odds of delayed graft dysfunction increase by about 161%, holding the other variables constant. The confidence interval is fairly wide, which reflects some uncertainty in the estimate, but it lies entirely above 1.0 — suggesting the positive association is reasonably consistent.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Odds Ratios and 95\% Confidence Intervals (Reduced Model)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Odds Ratio</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2.5\% CI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">97.5\% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.547</td>
</tr>
<tr class="even">
<td style="text-align: left;">$\log_2$(glucose)</td>
<td style="text-align: right;">1.328</td>
<td style="text-align: right;">0.794</td>
<td style="text-align: right;">2.234</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">donorrisk</td>
<td style="text-align: right; font-weight: bold;">2.606</td>
<td style="text-align: right; font-weight: bold;">1.372</td>
<td style="text-align: right; font-weight: bold;">4.974</td>
</tr>
<tr class="even">
<td style="text-align: left;">sex (female)</td>
<td style="text-align: right;">0.964</td>
<td style="text-align: right;">0.598</td>
<td style="text-align: right;">1.540</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Odds ratios = exp(coef(m0)). CIs via profiled log-likelihood.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</section>
<section id="visualization" class="level2">
<h2 class="anchored" data-anchor-id="visualization">Visualization</h2>
<p>Figure 1 shows the predicted probability of delayed graft dysfunction across the range of observed DRI values. The upward trend is fairly clear — donors with higher risk scores are predicted to have a higher probability of DGD. The confidence band is tighter at lower DRI values where there are more observations, and widens toward the upper end where data are sparser.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="project_files/figure-html/fig1-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption>Predicted probability of delayed graft dysfunction as a function of Donor Risk Index, with 95% confidence band. Fitted from a binomial GLM using geom_smooth().</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>Overall, our results suggest that donor risk index is a meaningful predictor of delayed graft dysfunction, while donor glucose does not appear to add much on top of what DRI already captures — at least in this dataset and with this modeling approach.</p>
<p>The odds ratio for DRI was about 2.61, which seems like a substantial effect, though we want to be careful about over-interpreting a single model with limited covariates. The confidence interval (1.40 to 5.07) is wide enough that there is real uncertainty around this estimate. Still, the direction is clear and the result is statistically significant, which gives us some confidence that DRI is picking up on something real.</p>
<p>The non-significance of glucose was somewhat surprising given our initial hypothesis, but there are a few reasonable explanations. It is possible that DRI already captures much of what glucose reflects — donors with high DRI scores tend to be older and sicker, which could also drive elevated glucose. If that is the case, glucose may not tell us much beyond what DRI already does. It is also possible that a glucose effect exists but that our sample of 437 complete cases was not large enough to detect it reliably, especially after 135 observations were dropped due to missingness. We cannot really distinguish between these two explanations with the data we have.</p>
<p>There are a few other limitations worth mentioning. Our model only includes three predictors, and there are likely other variables — such as cold ischemia time or recipient-level factors — that could matter and are not accounted for here. Because this is observational data, we also cannot make any causal claims. A higher DRI being associated with more dysfunction does not mean DRI causes it; both could be driven by underlying donor characteristics we are not measuring. We also handled missing data by dropping incomplete cases, which is simple but may introduce bias if the missingness is related to the outcome.</p>
<p>If we were to extend this analysis, multiple imputation could help recover some of the information lost from the 135 dropped observations. Including additional clinical variables would also likely improve the model. It would also be interesting to look at glucose at different time points rather than just a time-weighted average, to see if timing matters.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>We used logistic regression to examine whether donor glucose predicts delayed graft dysfunction and whether that relationship is modified by donor risk index. The interaction between glucose and DRI was not statistically significant (LRT <span class="math inline">\(p\)</span> = 0.32), and glucose itself was not a significant predictor in the reduced model (<span class="math inline">\(p\)</span> = 0.28). Donor risk index, on the other hand, showed a consistent positive association with DGD across both models, with an estimated odds ratio of 2.61 (95% CI: 1.40 to 5.07).</p>
<p>Based on these results, DRI appears to be the stronger predictor of graft dysfunction in this dataset, and glucose did not provide meaningful additional information beyond it. That said, our model is relatively simple and there is quite a bit of uncertainty in some of our estimates, so these findings should be interpreted cautiously rather than as definitive conclusions. We are 95% confident that a one-unit increase in donor risk is associated with between 1.4× and 5.1× higher odds of graft dysfunction.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>